// Mocks generated by Mockito 5.4.6 from annotations
// in hrm/test/features/chat/logic/cubit/chat_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;

import 'package:hrm/features/chat/data/models/conversation_model.dart' as _i5;
import 'package:hrm/features/chat/data/models/message_model.dart' as _i2;
import 'package:hrm/features/chat/data/repo/chat_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMessageModel_0 extends _i1.SmartFake implements _i2.MessageModel {
  _FakeMessageModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i3.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.ConversationModel>> getConversations({
    required int? companyId,
    required int? currentUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getConversations, [], {
              #companyId: companyId,
              #currentUserId: currentUserId,
            }),
            returnValue: _i4.Future<List<_i5.ConversationModel>>.value(
              <_i5.ConversationModel>[],
            ),
          )
          as _i4.Future<List<_i5.ConversationModel>>);

  @override
  _i4.Future<int> createConversation({
    required int? companyId,
    required List<int>? userIds,
    String? type,
    String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createConversation, [], {
              #companyId: companyId,
              #userIds: userIds,
              #type: type,
              #name: name,
            }),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i2.MessageModel>> getMessages({
    required int? conversationId,
    required int? companyId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [], {
              #conversationId: conversationId,
              #companyId: companyId,
            }),
            returnValue: _i4.Future<List<_i2.MessageModel>>.value(
              <_i2.MessageModel>[],
            ),
          )
          as _i4.Future<List<_i2.MessageModel>>);

  @override
  _i4.Future<_i2.MessageModel> sendMessage({
    required int? conversationId,
    required int? companyId,
    String? message,
    _i6.File? attachment,
    String? attachmentType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #conversationId: conversationId,
              #companyId: companyId,
              #message: message,
              #attachment: attachment,
              #attachmentType: attachmentType,
            }),
            returnValue: _i4.Future<_i2.MessageModel>.value(
              _FakeMessageModel_0(
                this,
                Invocation.method(#sendMessage, [], {
                  #conversationId: conversationId,
                  #companyId: companyId,
                  #message: message,
                  #attachment: attachment,
                  #attachmentType: attachmentType,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.MessageModel>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getUsers(int? companyId) =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, [companyId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);
}
